name: za_warudo
description: A Flutter application with timer and alarm features.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.5

  flutter_localizations:
    sdk: flutter

  audioplayers: ^6.5.0
  vibration: ^3.1.3
  torch_light: ^1.1.0
  shared_preferences: ^2.5.3

  file_picker: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
  generate: true
  # Localization config
  # The l10n directory is the default for ARB files
  # If you want to customize, uncomment and edit below:
  # l10n:
  #   arb-dir: lib/l10n
  #   template-arb-file: app_en.arb
  #   output-localization-file: app_localizations.dart
